name: project12
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  blurrycontainer: ^0.0.1
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  fonts:
    - family: Radiate Sans
      fonts: 
        - asset: assets/fonts/Radiate Sans Regular Semi Expanded.ttf
        - asset: assets/fonts/Radiate Sans Regular Semi Expanded Italic.ttf
        - asset: assets/fonts/Radiate Sans Light.ttf
        - asset: assets/fonts/Radiate Sans Bold Condensed italic.ttf
        - asset: assets/fonts/Radiate Sans Bold Condensed.ttf
        - asset: assets/fonts/Radiate Sans Extra Bold Italic.ttf
        - asset: assets/fonts/Radiate Sans Bold Expanded.ttf
        - asset: assets/fonts/Radiate Sans Light Condensed.ttf
        - asset: assets/fonts/Radiate Sans Light Semi Expanded Italic.ttf
        - asset: assets/fonts/Radiate Sans Regular Expanded.ttf
        - asset: assets/fonts/Radiate Sans Regular.ttf
        - asset: assets/fonts/Radiate Sans Semi Bold Italic.ttf
    - family: SF Pro Text Medium
      fonts:
        - asset: assets/fonts/SFProTextMedium.ttf
    - family: SF Pro Text Regular
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf

    